config/routes.rb
Mentorminder::Application.routes.draw do

  
  devise_for :users,
              controllers: {registrations: "my_devise/registrations"}
  as :user do
    get 'users/edit' => 'my_devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'my_devise/registrations#update', :as => 'user_registration'
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get '/profile/edit', to: 'dashboard#user_profile_edit'
    put 'profile/edit', to: 'dashboard#user_profile_update'
    resources :users

  end

  resources :events do
    collection do
      match 'search' => 'events#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentors do 
    collection do
      match 'search' => 'mentors#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentor_regs do
    member do
      post :process_reg
    end
    collection do
      get :thanks
    end
  end

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@mentors = Mentor.all
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">

  <div class="col-md-4">
    <div class="dashboardBox dashboardHello">
      <h1 class = "removeMargin">Hello,</h1>
      <p class="dashboardTitle"> 
        <%= current_user.username %>! </p>
    </div>

    <div class="dashboardBox dashboardHello">
      <p class="dashboardTitle green">Last event:</p>
      <li>
        <img class="dashboardImage" src="assets/calendar.png">
        <% Event.most_recent.order('event_date DESC').limit(1).each do |event| %>
          <%= link_to event.topic, event %>
        <% end %>
      </li>
    </div>
  </div>

  <div class="col-md-4">
    <div class="dashboardBox monitor">
      <br>
      <br>
      <p class="dashboardTitle orange"> Upcoming:</p>
      <% Event.upcoming.order('event_date').limit(3).each do |event| %>
      <li><%= link_to event.topic, event %></li>
      <% end %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="dashboardBox dashboardHello">
      <a href="https://bufferapp.com/"><img class="dashboardImage" src="assets/buffer.png"></a><a href="https://twitter.com/llcodedotcom"><img class="dashboardImage" src="assets/twitter.png"></a><a href="https://www.facebook.com/ladieslearningcode"><img class="dashboardImage" src="assets/facebook.png"></a>
    </div>

    <div class="dashboardBox dashboardHello">
      <a href="https://basecamp.com/"><img class="dashboardImage" src="assets/basecamp.png"></a><a href="http://learninglabs.org/wp-admin/"><img class="dashboardImage" src="assets/wordpress.png"></a><a href="http://mailchimp.com/"><img class="dashboardImage" src="assets/mailchimp.png"></a><a href="https://www.eventbrite.ca/"><img class="dashboardImage" src="assets/eventbrite.png"></a>
      <br>
      <br>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="dashboardBox">
      <p class="dashboardTitle blue">Approved Mentors:</p> 
      <p class="dashboardCount"><%= link_to Mentor.count, mentors_path %></p>
    </div>

    <div class="dashboardBox">
      <p class="dashboardTitle pink">Female Mentors:</p> 
       <p class="dashboardCount"><img class="mentorImage" src="assets/female.png"><%= Mentor.gendered('Female').count %></p>
    </div>
  </div>

  <div class="col-md-4">
    <div class="dashboardBox">
      <p class="dashboardTitle red">Pending Mentors:</p>
      <p class="dashboardCount"><%= link_to MentorReg.pending?.count, mentor_regs_path %></p>
    </div>

    <div class="dashboardBox">
      <p class="dashboardTitle lightBlue">Male Mentors:</p> 
      <p class="dashboardCount"><img class="mentorImage" src="assets/male.png"><%= Mentor.gendered('Male').count %></p>
    </div>
  </div>

  <div class="col-md-4">
    <div class="dashboardBox">
      <p class="dashboardTitle gold">Top Mentors:</p>
      <br>
      <img src="assets/trophy.png">
      <br>
      <br>
      <% @mentors.order('events_count').reverse_order.limit(5).each do |mentor| %>
      <li><%= link_to mentor.first_name, mentor %>: <%= mentor.events.size %> Events</li>
      <% end %>
      <br>
    </div>
  </div>
</div>