config/routes.rb
Mentorminder::Application.routes.draw do

  
  devise_for :users,
              controllers: {registrations: "my_devise/registrations"}
  as :user do
    get 'users/edit' => 'my_devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'my_devise/registrations#update', :as => 'user_registration'
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get '/profile/edit', to: 'dashboard#user_profile_edit'
    put 'profile/edit', to: 'dashboard#user_profile_update'
    resources :users

  end

  resources :events do
    collection do
      match 'search' => 'events#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentors do 
    collection do
      match 'search' => 'mentors#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentor_regs do
    member do
      post :process_reg
    end
    collection do
      get :thanks
    end
  end

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :sign_ups
	has_many :mentors, through: :sign_ups


	def self.upcoming
		where(['event_date > ?', Date.today])
	end

	def self.most_recent
		where(['event_date < ?', Date.today])
	end

	def mentors
		Mentor.joins(:sign_ups).where(sign_ups: { event_id: id })
	end
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
	has_many :sign_ups, as: :signupable
	has_many :events, through: :sign_ups


	def self.gendered (x)
		where(gender: x)
	end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @q = Event.search(params[:q])
    @events = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:category, :age_group, :topic, :event_date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_add_events.html.erb
<% Event.upcoming.order('event_date').each do |event| %>
	<%= check_box_tag 'event_ids[]', event.id %>
	<%= "#{event.topic} - #{event.event_date}" %><br>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= f.label :category %><br>
        <%= f.select :category, ([["Select One", ""], "Girls Learning Code", "Kids Learning Code"]) %>
      </div>
      <div class="field">
        <%= f.label :age_group %><br>
        <%= f.select :age_group, ([["Select One", ""], "6-8", "9-12", "13-16"]) %>
      </div>
      <div class="field">
        <%= f.label :topic %><br>
        <%= f.text_field :topic, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :event_date %><br>
        <%= f.date_select :event_date %>
      </div>

      <br>

      <div class="actions">
        <%= f.submit :class => 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1> <%= @event.topic %> </h1>

<br>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>Events <%= link_to 'Add New', new_event_path, :class => 'btn btn-success headerButton' %> </h1>

<form class="form-inline" role="form">
  <div class="form-group pull-right">
    <%= search_form_for @q do |f| %>
      <%= f.search_field :topic_cont, :placeholder => "Topic", class: "form-control search" %>
      <%= f.submit class: "btn btn-default" %>
    <% end %>
  </div>
</form>

<br>
<br>

<table class="table homeTable">
  <thead>
    <tr>
      <th><%= sort_link @q, :category, "Category" %></th>
      <th><%= sort_link @q, :age_group, "Age Group" %></th>
      <th><%= sort_link @q, :topic, "Topic" %></th>
      <th><%= sort_link @q, :event_date, "Event Date" %></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.category %></td>
        <td><%= event.age_group %></td>
        <td><%= event.topic %></td>
        <td><%= event.event_date %></td>
        <td><%= link_to 'Profile', event, :class => "btn btn-info pull-right" %></td>
        <td><%= link_to 'Edit', edit_event_path(event), :class => "btn btn-warning pull-right" %></td>
        <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger pull-right' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @events %>

app/views/events/new.html.erb
<h1>Add Event</h1>

<br>

<%= render 'form' %>

app/views/events/show.html.erb
<h1> <%= @event.topic %> <%= link_to 'Edit', edit_event_path(@event), :class => 'btn btn-warning headerButton' %> </h1>

<br>

<p>
  <strong>Category:</strong>
  <%= @event.category %>
</p>

<p>
  <strong>Age group:</strong>
  <%= @event.age_group %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @event.topic %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<br>
<br>

<table class="table">
	<thead>
		<tr>
			<th> First Name </th>
			<th> Last Name </th>
			<th> Email </th>
		</tr>
	</thead>

	<tbody>
		<% @event.mentors.each do |mentor| %>
			<tr>
				<td><%= mentor.first_name %></td>
				<td><%= mentor.last_name %></td>
				<td><%= mentor.email %></td>
			</tr>
		<% end %>
	</tbody>

</table>