config/routes.rb
Mentorminder::Application.routes.draw do

  
  devise_for :users,
              controllers: {registrations: "my_devise/registrations"}
  as :user do
    get 'users/edit' => 'my_devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'my_devise/registrations#update', :as => 'user_registration'
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get '/profile/edit', to: 'dashboard#user_profile_edit'
    put 'profile/edit', to: 'dashboard#user_profile_update'
    resources :users

  end

  resources :events do
    collection do
      match 'search' => 'events#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentors do 
    collection do
      match 'search' => 'mentors#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentor_regs do
    member do
      post :process_reg
    end
    collection do
      get :thanks
    end
  end

  root 'home#index'

end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
	has_many :sign_ups, as: :signupable
	has_many :events, through: :sign_ups


	def self.gendered (x)
		where(gender: x)
	end


end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: [:show, :edit, :update, :destroy]

  # GET /mentors
  # GET /mentors.json
  def index
    @q = Mentor.search(params[:q])
    @mentors = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /mentors/1
  # GET /mentors/1.json
  def show
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end


  # POST /mentors
  # POST /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mentor }
      else
        format.html { render action: 'new' }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1
  # PATCH/PUT /mentors/1.json
  def update
    events = params[:event_ids]
    if events
      events.each do |event|
        Mentor.find(params[:id]).sign_ups.where(event_id: event).first_or_create
      end
    end
 
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: 'Mentor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1
  # DELETE /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mentor_params
      params.require(:mentor).permit(:first_name, :last_name, :email, :gender, :first_aid_certified)
    end
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/views/mentors/_form.html.erb
<%= form_for(@mentor) do |f| %>
  <% if @mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
      <% @mentor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= f.label :first_name %><br>
          <%= f.text_field :first_name, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :gender %><br>
        <%= f.select :gender, ([["Select One", ""], "Female", "Male"]) %>
      </div>
      <div class="field">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :website %><br>
        <%= f.text_field :website, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :twitter %><br>
        <%= f.text_field :twitter, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :linkedin %><br>
        <%= f.text_field :linkedin, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :work %><br>
        <%= f.text_field :work, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :job %><br>
        <%= f.text_field :job, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :bio %><br>
        <%= f.text_area :bio, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :why_involved %><br>
        <%= f.text_area :why_involved, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :emergency_contact %><br>
        <%= f.text_field :emergency_contact, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :references %><br>
        <%= f.text_area :references, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.check_box :permission_to_contact_references %>
        <%= f.label :permission_to_contact_references %>
      </div>
      <div class="field">
        <%= f.check_box :first_aid_certified %>
        <%= f.label :first_aid_certified %>
      </div>

      <br>
  
      <%= render 'events/add_events' %>

      <br>

      <div class="actions">
        <%= f.submit :class => 'btn btn-success' %> 
    </div>
  </div>
<% end %>

app/views/mentors/edit.html.erb
<h1> <%= @mentor.first_name %> <%= @mentor.last_name %> </h1>

<br>

<%= render 'form' %>

app/views/mentors/index.html.erb
<h1>Mentors <%= link_to 'Add New', new_mentor_path, :class => 'btn btn-success headerButton' %> </h1>

<form class="form-inline" role="form">
  <div class="form-group pull-right">
    <%= search_form_for @q do |f| %>
      <%= f.search_field :first_name_or_last_name_or_email_cont, :placeholder => "First Name/Last Name/Email", class: "form-control search" %>
      <%= f.submit class: "btn btn-default" %>
    <% end %>
  </div>
</form>

<br>
<br>

<table class="table homeTable">
  <thead>
      <th><%= sort_link @q, :first_name, "First Name" %></th>
      <th><%= sort_link @q, :last_name, "Last Name" %></th>
      <th><%= sort_link @q, :email, "Email" %></th>
      <th><%= sort_link @q, :first_aid_certified, "First Aid Certified?" %></th>
  </thead>

  <tbody>
    <% @mentors.each do |mentor| %>
      <tr>
        <td><%= link_to mentor.first_name, mentor %></td>
        <td><%= link_to mentor.last_name, mentor %></td>
        <td><%= mentor.email %></td>
        <td><%= mentor.first_aid_certified %></td>
        
        <td>
<%= link_to 'Profile', mentor, :class => 'btn btn-info pull-right' %></td>
        <td>
<%= link_to 'Edit', edit_mentor_path(mentor), :class => 'btn btn-warning pull-right' %></td>
        <td>
<%= link_to 'Delete', mentor, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger pull-right' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @mentors %>

app/views/mentors/new.html.erb
<h1>New mentor</h1>

<br>

<%= render 'form' %>

app/views/mentors/show.html.erb
<h1> <%= @mentor.first_name %> <%= @mentor.last_name %> <%= link_to 'Edit', edit_mentor_path(@mentor), :class => 'btn btn-warning headerButton' %> </h1>

<br>

<p>
  <strong>First Name:</strong>
  <%= @mentor.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @mentor.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mentor.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @mentor.gender %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @mentor.phone %>
</p>

<p>
  <strong>City:</strong>
  <%= @mentor.city %>
</p>

<p>
  <strong>Website:</strong>
  <%= @mentor.website %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @mentor.twitter %>
</p>

<p>
  <strong>LinkedIn:</strong>
  <%= @mentor.linkedin %>
</p>

<p>
  <strong>Work:</strong>
  <%= @mentor.work %>
</p>

<p>
  <strong>Job:</strong>
  <%= @mentor.job %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @mentor.bio %>
</p>

<p>
  <strong>Why Involved:</strong>
  <%= @mentor.why_involved %>
</p>

<p>
  <strong>Emergency Contact:</strong>
  <%= @mentor.emergency_contact %>
</p>

<p>
  <strong>References:</strong>
  <%= @mentor.references %>
</p>

<p>
  <strong>Permission to contact references:</strong>
  <%= @mentor.permission_to_contact_references %>
</p>

<p>
  <strong>First Aid Certified:</strong>
  <%= @mentor.first_aid_certified %>
</p>

<br>
<br>

<table class="table">
	<thead>
		<tr>
			<th>Category</th>
			<th>Age Group</th>
			<th>Topic</th>
      <th>Event Date</th>
		</tr>
	</thead>
	<tbody>
		<% @mentor.events.each do |event| %>
			<tr>
        <td><%= event.category %></td>
        <td><%= event.age_group %></td>
				<td><%= event.topic %></td>
        <td><%= event.event_date %></td>
			</tr>
		<% end %>
	</tbody>
</table>


</p>