config/routes.rb
Mentorminder::Application.routes.draw do

  
  devise_for :users,
              controllers: {registrations: "my_devise/registrations"}
  as :user do
    get 'users/edit' => 'my_devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'my_devise/registrations#update', :as => 'user_registration'
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get '/profile/edit', to: 'dashboard#user_profile_edit'
    put 'profile/edit', to: 'dashboard#user_profile_update'
    resources :users

  end

  resources :events do
    collection do
      match 'search' => 'events#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentors do 
    collection do
      match 'search' => 'mentors#index', :via => [:get, :post], :as => :search
    end
  end

  resources :mentor_regs do
    member do
      post :process_reg
    end
    collection do
      get :thanks
    end
  end

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save 
			flash[:notice] = "Successfully created new user"
		else
			flash[:notice] = "Save failed"
		end
		redirect_to admin_users_path

	end

	def show
	end

	def edit
	end

	def update
		if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
    		params[:user].delete(:password)
    		params[:user].delete(:password_confirmation)
		end

		if @user.update(user_params) 
			flash[:notice] = "Update successful"
		else 
			flash[:notice] = "Update failed"
		end
		redirect_to admin_users_path
	end

	def destroy
		if @user.destroy
			flash[:notice] = "User deleted"
		else
			flash[:notice] = "User destroy failed"
		end
		redirect_to admin_users_path

	end

	private

	def set_user
      @user = User.find(params[:id])
    end

	def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :username %><br />
        <%= f.text_field :username, :class => 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, :class => 'form-control'%>
      </div>

      <br>

      <div class="actions">
        <%= f.submit "Submit", :class => 'btn btn-success' %>
      </div>
    </div>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<h1> <%= @user.username %> </h1>

<br>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Users <%= link_to "Create User", new_admin_user_path, :class => 'btn btn-success headerButton' %></h1>

<br>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, admin_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Edit", edit_admin_user_path(user), :class => 'btn btn-warning pull-right' %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger pull-right' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<br>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1> <%= @user.username %> </h1>

<br>

<p id="notice"><%= notice %></p>

<p>
  <strong>Username</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_admin_user_path(@user) %> |